# ~/.config/starship.toml

# custom format
#format= '$all'

command_timeout=100

## FIRST LINE/ROW: Info & Status
# First param ─┌
[username]
format = " [╭─$user]($style)@"
style_user = "bold green"
style_root = "bold blue"
show_always = true

# Second param
[hostname]
format = "[$hostname]($style) in "
style = "bold dimmed green"
trim_at = "-"
ssh_only = false
disabled = false

# Third param
[directory]
style = "purple"
truncation_length = 3
truncate_to_repo = true
truncation_symbol = "repo: "

# Before all the version info (python, nodejs, php, etc.)
[git_status]
style = "white"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
deleted = "x"

# Last param in the first line/row
[cmd_duration]
min_time = 1
format = "took [$duration]($style)"
disabled = false
style = "bold white"
show_notifications = true
min_time_to_notify = 45_000

## SECOND LINE/ROW: Prompt
# Somethere at the beginning

# Prompt: param 2 └─
[character]
success_symbol = " [╰─>](bold green)"
error_symbol = " [╰─x](bold red)"
#use_symbol_for_status = true


[battery]
disabled = true

[[battery.display]]  # "bold red" style when capacity is between 0% and 10%
threshold = 15
style = "bold red"

[[battery.display]]  # "bold yellow" style when capacity is between 10% and 30%
threshold = 50
style = "bold yellow"

[[battery.display]]  # "bold green" style when capacity is between 10% and 30%
threshold = 80
style = "bold green"

# Prompt: optional param 1
[time]
format = " 🕙 $time($style)"
time_format = "%T"
style = "bright-white"
disabled = true



[c]
detect_extensions = ['c', 'h', 'hpp', 'cpp']
commands = [ ["cc", "--version"], ["gcc", "--version"], ["clang", "--version"], ["g++", "--version"] ]

[git_branch]
symbol = '🌱 '
truncation_length = 4
truncation_symbol = ''
